version: '3'
services:
     web:
         container_name: web_tech_interview
         build: .
         tty: true
         volumes:
             - .:/go/app
         ports:
             - "8080:8080"
     nginx:
         image: nginx:latest
         container_name: nginx_tech_interview
         ports:
             - "80:80"
         depends_on:
             - web
         volumes:
             # mount NGINX config file
             - ./nginx/default.conf:/etc/nginx/conf.d/default.conf